<?php
/**
 * Vehicle Details ACF Field Group
 *
 * @package vroomqc
 */

// Prevent direct access
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

add_action( 'acf/include_fields', function() {
    if ( ! function_exists( 'acf_add_local_field_group' ) ) {
        return;
    }

    acf_add_local_field_group( array(
        'key' => 'group_vehicle_taxonomy_fields',
        'title' => 'Vehicle Details',
        'fields' => array(
            array(
                'key' => 'field_vehicle_vin',
                'label' => 'VIN Number',
                'name' => 'vin',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => 'Enter the vehicle VIN number and click lookup to fetch vehicle details',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => 'acf-field-vin-first',
                    'id' => '',
                ),
                'maxlength' => 17,
                'placeholder' => 'Enter 17-character VIN',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_683088497ee29',
                'label' => 'Vehicle gallery',
                'name' => 'vehicle_gallery',
                'aria-label' => '',
                'type' => 'gallery',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'library' => 'all',
                'min' => '',
                'max' => '',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'insert' => 'append',
                'preview_size' => 'medium',
            ),
            array(
                'key' => 'field_683a8c1a21b02',
                'label' => 'Vendu',
                'name' => 'vendu',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'allow_in_bindings' => 0,
                'ui_on_text' => 'Vendu',
                'ui_off_text' => 'Pas Vendu',
                'ui' => 1,
            ),
            array(
                'key' => 'field_price',
                'label' => 'Price (CAD)',
                'name' => 'price',
                'aria-label' => '',
                'type' => 'number',
                'instructions' => '',
                'required' => false,
                'conditional_logic' => false,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'min' => '',
                'max' => '',
                'step' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_old_price',
                'label' => 'Old Price (CAD)',
                'name' => 'old_price',
                'aria-label' => '',
                'type' => 'number',
                'instructions' => 'Enter the original price before discount. Leave empty if no discount.',
                'required' => false,
                'conditional_logic' => false,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'min' => '',
                'max' => '',
                'step' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_carfax_url',
                'label' => 'Carfax Report URL',
                'name' => 'carfax_url',
                'aria-label' => '',
                'type' => 'url',
                'instructions' => '',
                'required' => false,
                'conditional_logic' => false,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_biweekly_payment',
                'label' => 'Biweekly Payment',
                'name' => 'biweekly_payment',
                'aria-label' => '',
                'type' => 'number',
                'instructions' => '',
                'required' => false,
                'conditional_logic' => false,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'min' => '',
                'max' => '',
                'step' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_mileage',
                'label' => 'Odometer (km)',
                'name' => 'mileage',
                'aria-label' => '',
                'type' => 'number',
                'instructions' => '',
                'required' => false,
                'conditional_logic' => false,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'min' => '',
                'max' => '',
                'step' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_engine',
                'label' => 'Engine Type',
                'name' => 'engine',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => false,
                'conditional_logic' => false,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_doors',
                'label' => 'Doors',
                'name' => 'doors',
                'aria-label' => '',
                'type' => 'number',
                'instructions' => '',
                'required' => false,
                'conditional_logic' => false,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'min' => '',
                'max' => '',
                'step' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_seats',
                'label' => 'Seats',
                'name' => 'seats',
                'aria-label' => '',
                'type' => 'number',
                'instructions' => '',
                'required' => false,
                'conditional_logic' => false,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'min' => '',
                'max' => '',
                'step' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_fuel_city',
                'label' => 'Fuel Economy (City)',
                'name' => 'fuel_city',
                'aria-label' => '',
                'type' => 'number',
                'instructions' => '',
                'required' => false,
                'conditional_logic' => false,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'min' => '',
                'max' => '',
                'step' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_fuel_hwy',
                'label' => 'Fuel Economy (Hwy)',
                'name' => 'fuel_hwy',
                'aria-label' => '',
                'type' => 'number',
                'instructions' => '',
                'required' => false,
                'conditional_logic' => false,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'min' => '',
                'max' => '',
                'step' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_short_description',
                'label' => 'Short Description',
                'name' => 'short_description',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => '',
                'required' => false,
                'conditional_logic' => false,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'new_lines' => '',
                'maxlength' => '',
                'placeholder' => '',
                'rows' => '',
            ),
            array(
                'key' => 'field_long_description',
                'label' => 'Long Description',
                'name' => 'long_description',
                'aria-label' => '',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => false,
                'conditional_logic' => false,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
                'default_value' => '',
                'delay' => 0,
            ),
            array(
                'key' => 'field_displacementL',
                'label' => 'Engine Displacement (L)',
                'name' => 'displacementL',
                'aria-label' => '',
                'type' => 'number',
                'instructions' => '',
                'required' => false,
                'conditional_logic' => false,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'min' => '',
                'max' => '',
                'step' => '0.1',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_cylinder_number',
                'label' => 'Cylinders (Number)',
                'name' => 'cylinder',
                'aria-label' => '',
                'type' => 'number',
                'instructions' => '',
                'required' => false,
                'conditional_logic' => false,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'min' => '',
                'max' => '',
                'step' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_options',
                'label' => 'Vehicle Options',
                'name' => 'options',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => '',
                'required' => false,
                'conditional_logic' => false,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'new_lines' => '',
                'maxlength' => '',
                'placeholder' => '',
                'rows' => '',
            ),
            array(
                'key' => 'field_fuel_capacity',
                'label' => 'Fuel Capacity (L)',
                'name' => 'fuel_capacity',
                'aria-label' => '',
                'type' => 'number',
                'instructions' => '',
                'required' => false,
                'conditional_logic' => false,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'min' => '',
                'max' => '',
                'step' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_msrp',
                'label' => 'MSRP (CAD)',
                'name' => 'msrp',
                'aria-label' => '',
                'type' => 'number',
                'instructions' => '',
                'required' => false,
                'conditional_logic' => false,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'min' => '',
                'max' => '',
                'step' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'vehicle',
                ),
            ),
        ),
        'menu_order' => -1,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ) );
} );