<?php
/**
 * Vehicle Taxonomies ACF Field Group
 *
 * @package vroomqc
 */

// Prevent direct access
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

add_action( 'acf/include_fields', function() {
    if ( ! function_exists( 'acf_add_local_field_group' ) ) {
        return;
    }

    acf_add_local_field_group( array(
        'key' => 'group_vehicle_taxonomies',
        'title' => 'Vehicle Taxonomies',
        'fields' => array(
            array(
                'key' => 'field_682f7171242ae',
                'label' => 'Year',
                'name' => 'year',
                'aria-label' => '',
                'type' => 'number',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'min' => 2000,
                'max' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'step' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_vehicle_tax_make',
                'label' => 'Make',
                'name' => 'make',
                'aria-label' => '',
                'type' => 'taxonomy',
                'instructions' => '',
                'required' => false,
                'conditional_logic' => false,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'taxonomy' => 'make',
                'field_type' => 'select',
                'add_term' => true,
                'save_terms' => true,
                'load_terms' => true,
                'return_format' => 'id',
                'multiple' => false,
                'allow_null' => 0,
                'bidirectional_target' => array(
                ),
            ),
            array(
                'key' => 'field_vehicle_tax_model',
                'label' => 'Model',
                'name' => 'model',
                'aria-label' => '',
                'type' => 'taxonomy',
                'instructions' => '',
                'required' => false,
                'conditional_logic' => false,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'taxonomy' => 'model',
                'field_type' => 'select',
                'add_term' => true,
                'save_terms' => true,
                'load_terms' => true,
                'return_format' => 'id',
                'multiple' => false,
                'allow_null' => 0,
                'bidirectional_target' => array(
                ),
            ),
            array(
                'key' => 'field_vehicle_tax_trim',
                'label' => 'Trim',
                'name' => 'trim',
                'aria-label' => '',
                'type' => 'taxonomy',
                'instructions' => '',
                'required' => false,
                'conditional_logic' => false,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'taxonomy' => 'trim',
                'field_type' => 'select',
                'add_term' => true,
                'save_terms' => true,
                'load_terms' => true,
                'return_format' => 'id',
                'multiple' => false,
                'allow_null' => 0,
                'bidirectional_target' => array(
                ),
            ),
            array(
                'key' => 'field_vehicle_tax_fuel_type',
                'label' => 'Fuel Type',
                'name' => 'fuel-type',
                'aria-label' => '',
                'type' => 'taxonomy',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'taxonomy' => 'fuel-type',
                'add_term' => 1,
                'save_terms' => 1,
                'load_terms' => 1,
                'return_format' => 'id',
                'field_type' => 'select',
                'allow_null' => 0,
                'allow_in_bindings' => 1,
                'bidirectional' => 0,
                'multiple' => 0,
                'bidirectional_target' => array(
                ),
            ),
            array(
                'key' => 'field_vehicle_tax_transmission',
                'label' => 'Transmission',
                'name' => 'transmission',
                'aria-label' => '',
                'type' => 'taxonomy',
                'instructions' => '',
                'required' => false,
                'conditional_logic' => false,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'taxonomy' => 'transmission',
                'field_type' => 'select',
                'add_term' => true,
                'save_terms' => true,
                'load_terms' => true,
                'return_format' => 'id',
                'multiple' => false,
                'allow_null' => 0,
                'bidirectional_target' => array(
                ),
            ),
            array(
                'key' => 'field_vehicle_tax_drivetrain',
                'label' => 'Drivetrain',
                'name' => 'drivetrain',
                'aria-label' => '',
                'type' => 'taxonomy',
                'instructions' => '',
                'required' => false,
                'conditional_logic' => false,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'taxonomy' => 'drivetrain',
                'field_type' => 'select',
                'add_term' => true,
                'save_terms' => true,
                'load_terms' => true,
                'return_format' => 'id',
                'multiple' => false,
                'allow_null' => 0,
                'bidirectional_target' => array(
                ),
            ),
            array(
                'key' => 'field_vehicle_tax_body_style',
                'label' => 'Body Style',
                'name' => 'body-style',
                'aria-label' => '',
                'type' => 'taxonomy',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'taxonomy' => 'body-style',
                'add_term' => 1,
                'save_terms' => 1,
                'load_terms' => 1,
                'return_format' => 'id',
                'field_type' => 'select',
                'allow_null' => 0,
                'allow_in_bindings' => 1,
                'bidirectional' => 0,
                'multiple' => 0,
                'bidirectional_target' => array(
                ),
            ),
            array(
                'key' => 'field_vehicle_tax_cylinders',
                'label' => 'Cylinders',
                'name' => 'cylinder',
                'aria-label' => '',
                'type' => 'taxonomy',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'taxonomy' => 'cylinder',
                'add_term' => 1,
                'save_terms' => 1,
                'load_terms' => 1,
                'return_format' => 'id',
                'field_type' => 'select',
                'allow_null' => 0,
                'allow_in_bindings' => 1,
                'bidirectional' => 0,
                'multiple' => 0,
                'bidirectional_target' => array(
                ),
            ),
            array(
                'key' => 'field_vehicle_tax_exterior_color',
                'label' => 'Exterior Color',
                'name' => 'exterior-color',
                'aria-label' => '',
                'type' => 'taxonomy',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'taxonomy' => 'exterior-color',
                'add_term' => 1,
                'save_terms' => 1,
                'load_terms' => 1,
                'return_format' => 'id',
                'field_type' => 'select',
                'allow_null' => 1,
                'allow_in_bindings' => 1,
                'bidirectional' => 0,
                'multiple' => 0,
                'bidirectional_target' => array(
                ),
            ),
            array(
                'key' => 'field_vehicle_tax_interior_color',
                'label' => 'Interior Color',
                'name' => 'interior-color',
                'aria-label' => '',
                'type' => 'taxonomy',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'taxonomy' => 'interior-color',
                'add_term' => 1,
                'save_terms' => 1,
                'load_terms' => 1,
                'return_format' => 'id',
                'field_type' => 'select',
                'allow_null' => 1,
                'allow_in_bindings' => 1,
                'bidirectional' => 0,
                'multiple' => 0,
                'bidirectional_target' => array(
                ),
            ),
            array(
                'key' => 'field_682f696d604e0',
                'label' => 'Manufacturer',
                'name' => 'manufacturer',
                'aria-label' => '',
                'type' => 'taxonomy',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'taxonomy' => 'manufacturer',
                'add_term' => 1,
                'save_terms' => 1,
                'load_terms' => 1,
                'return_format' => 'id',
                'field_type' => 'select',
                'allow_null' => 1,
                'allow_in_bindings' => 0,
                'bidirectional' => 0,
                'multiple' => 0,
                'bidirectional_target' => array(
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'vehicle',
                ),
            ),
        ),
        'menu_order' => 2,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ) );
} );